- id: '1788148813073'
  alias: Driveway person light
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.driveway_person_occupancy
    to:
    - 'on'
  conditions:
  - condition: sun.is_set
    options: {}
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.frontcam_illuminator
    data: {}
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.frontcam_illuminator
    data: {}
  mode: single
